version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: me@admin
      MYSQL_DATABASE: maosencantadas
      MYSQL_USER: meadmn
      MYSQL_PASSWORD: me@admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
