api:
  security:
    token:
      secret: ${JWT_SECRET:6806c6a4246f7181bb23c6b8b2c3ed647a25d28665b9bad83f002c60afd06e8d}
file:
  upload-dir: uploads
server:
  error:
    whitelabel:
      enabled: false
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/maosencantadas?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: me@admin
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  flyway:
    locations: classpath:db/migration #, classpath:db/callback
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: file:uploads/
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true